# Generated by Django 4.0.4 on 2022-05-16 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoDjango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 5, 16, 14, 40, 10, 852893), verbose_name='Publicado em')),
            ],
        ),
    ]
